-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNxe/xEjthKZ4rIwoAAUB0H3YErKEuptcGE/3iEm/YAGgCgYIKoZIzj0DAQehRANCAAT/nmm6iWZ73froHhuE15bZkn/GpGVmTFOBMxysET8Tg1Xtpm49ZtbA8RzE5+IurR5tp3dCBJxoFWSp4MYYLCJu
-----END PRIVATE KEY-----